//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgLodigiani.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int ID { get; set; }
        public string VIDEO1 { get; set; }
        public string URL { get; set; }
        public string TIPO { get; set; }
        public System.DateTime DATA { get; set; }
        public string CATEGORIA { get; set; }
        public string ANNO { get; set; }
        public string MESE { get; set; }
        public Nullable<int> ATLETA { get; set; }
        public string AVVERSARIO { get; set; }
        public string NOTE { get; set; }
    
        public virtual ATLETA ATLETA1 { get; set; }
        public virtual CATEGORIA CATEGORIA1 { get; set; }
    }
}
